#!/bin/bash

# RUNME using "source setup-tapif" to get exported PRECONFIGURED_TAPIF variable

sudo ip tuntap add dev tap0 mode tap user `whoami`
sudo ip link set tap0 up
sudo ip addr add 192.168.0.1/24 dev tap0
export PRECONFIGURED_TAPIF=tap0
